name: Build and Push Docker

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        id: config
        uses: actions/github-script@v7
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        with:
          script: |-
            const {
              GITHUB_REF_NAME: ref_name,
            } = process.env

            core.setOutput('nproc', require('os').cpus().length * 2 + 1)
            core.setOutput('ref_name', ref_name)
            core.setOutput('version', context.sha.slice(0, 7))

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          echo "My variable is ${{ vars.TEST }}"
          echo "custom ref_name is ${{ steps.config.outputs.ref_name }}"
          echo "custom version is ${{ steps.config.outputs.version }}"

